name: Example workflow 

run-name: Example deploy 

on:

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    environment: 

      name: production

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Script
        run: node ./example-script.js
